// Note: This file is autogenerated using "scripts/gen-version.js" script and
// automatically updated by "npm version" command.

/**
 * A string containing the version of the Iris.js library
 */
export const version = '0.1.0' as string;

/**
 * An object containing the components of the Iris.js version string
 */
export const versionInfo = Object.freeze({
  major: 0 as number,
  minor: 1 as number,
  patch: 0 as number,
  preReleaseTag: null as string | null,
});
